### PR TITLE
Add Sketch for Helium DevKit using CayenneLPP

### PR DESCRIPTION
**Pull request by kent-williams**

### CODE REVIEW

**Comment by illperipherals** [comment]
If we make just a couple changes here, we can compile in both Arduino IDE and Platformio without issue. I pulled this into my Platformio workspace and imported the libs. This works great for a "core" devkit main. Do we want to add a hardware "send" interrupt here as well rather than making that a completely different "sketch"?
Oh, one note, I have the board I am using with platformio in jtag mode... thoughts there?

platformio.ini:
```
[env:disco_l072cz_lrwan1]
platform = ststm32
board = disco_l072cz_lrwan1
framework = arduino

upload_protocol = jlink
#upload_port = COM[6]

lib_deps =
     STM32duino X-NUCLEO-IKS01A3
     STM32duino LSM6DSO
     STM32duino LIS2DW12
     STM32duino STTS751
     STM32duino LIS2MDL
     STM32duino LPS22HH
     STM32duino HTS221
     MCCI LoRaWAN LMIC library
     CayenneLPP
     ArduinoJson
     CheckSum
     SPI
     Wire

```

**Review by illperipherals — COMMENTED** [review]
Just a small note, on things like "do_send", we may want to forward declare so we don't have a lot of compiler complaints.

**Comment by kent-williams** [comment]
> If we make just a couple changes here, we can compile in both Arduino IDE and Platformio without issue. I pulled this into my Platformio workspace and imported the libs. This works great for a "core" devkit main. Do we want to add a hardware "send" interrupt here as well rather than making that a completely different "sketch"?
> Oh, one note, I have the board I am using with platformio in jtag mode... thoughts there?
> 
> platformio.ini:
> 
> ```
> [env:disco_l072cz_lrwan1]
> platform = ststm32
> board = disco_l072cz_lrwan1
> framework = arduino
> 
> upload_protocol = jlink
> #upload_port = COM[6]
> 
> lib_deps =
>      STM32duino X-NUCLEO-IKS01A3
>      STM32duino LSM6DSO
>      STM32duino LIS2DW12
>      STM32duino STTS751
>      STM32duino LIS2MDL
>      STM32duino LPS22HH
>      STM32duino HTS221
>      MCCI LoRaWAN LMIC library
>      CayenneLPP
>      ArduinoJson
>      CheckSum
>      SPI
>      Wire
> ```

I have added a section to the readme including the required platformio.ini config.

We should try to use the default uploader/debugger utility, stlink, instead of jlink, specially since you need to reflash the on board debugger to even use jlink. 

The current PlatformIO board config file found [here](https://github.com/platformio/platform-ststm32/blob/6f38950430250ea315bbee628b95e5ed680deee0/boards/disco_l072cz_lrwan1.json#L23) is using the incorrect openocd script, but you can still get it to work by holding the reset right up until it initiates its routine, which I've added a note about. I'll be putting up a PR to request that fix.

**Comment by illperipherals** [comment]
Yep. I have a mix of boards some on ST-Link, some on segger. Thanks for the catch.

**Pull request merged**
